# Generated by Django 5.0.6 on 2024-07-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='child1',
        ),
        migrations.RemoveField(
            model_name='item',
            name='child2',
        ),
        migrations.RemoveField(
            model_name='item',
            name='child3',
        ),
        migrations.RemoveField(
            model_name='item',
            name='child4',
        ),
        migrations.AddField(
            model_name='item',
            name='college',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='elementary',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='secondary',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='vocational',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
